baseURL = "cabea.ir/"
title = "Ø§Ù†Ø¬Ù…Ù† Ù…Ù‡Ù†Ø¯Ø³ÛŒ Ù¾Ø²Ø´Ú©ÛŒ -  ØªÙ‡Ø±Ø§Ù† Ù…Ø±Ú©Ø²ÛŒ"
theme = "Mehraner-hugo"
timeZone = "Asia/Tehran"
# post pagination
paginate = 6 
summaryLength = 10 
googleAnalytics = "G-CHEBM9VFBO"
disqusShortname = "" # mehraner
disableLanguages = [] 
hasCJKLanguage = false

[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


[outputs]
home = ["HTML", "RSS"]

[imaging]
quality = 90
resampleFilter = "lanczos"

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe = true


[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

[params]
logo = "images/bme.png"
# Meta data
description = "Ø§Ø² Ø§ÛŒÙ† Ù¾Ø³ Ø§Ù†Ø¬Ù…Ù† Ù…Ù‡Ù†Ø¯Ø³ÛŒ Ù¾Ø²Ø´Ú©ÛŒ Ø¯Ø§Ù†Ø´Ú¯Ø§Ù‡ Ø¢Ø²Ø§Ø¯ ÙˆØ§Ø­Ø¯ ØªÙ‡Ø±Ø§Ù† Ù…Ø±Ú©Ø² Ø¯Ø§Ø±Ø§ÛŒ ÛŒÚ© Ù¾Ù„ØªÙØ±Ù… Ù…Ø³ØªÙ‚Ù„ Ø¨Ø±Ø§ÛŒ Ø§Ø±ØªØ¨Ø§Ø· Ø¨Ø§ Ø¯Ø§Ù†Ø´Ø¬Ùˆ Ùˆ Ù‡Ù…Ú†Ù†ÛŒÙ† Ø±Ø§Ø­ØªÛŒ Ø¯Ø§Ù†Ø´Ø¬ÙˆÛŒØ§Ù† Ø¹Ø²ÛŒØ² Ø¨Ø±Ø§ÛŒ Ø¯Ø±ÛŒØ§ÙØª Ù…Ù†Ø¸Ù… Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø¯Ø§Ù†Ø´Ú¯Ø§Ù‡ÛŒ Ø§Ø³Øª. ÙˆØ¨â€ŒØ³Ø§ÛŒØª Ø¯Ø± Ù…Ø±Ø§Ø­Ù„ Ø§Ø¨ØªØ¯Ø§ÛŒÛŒ ØªÙˆØ³Ø¹Ù‡ Ù‚Ø±Ø§Ø± Ø¯Ø§Ø±Ø¯. Ø¯Ø±Ù†ØªÛŒØ¬Ù‡ Ø§Ø² Ø´Ù…Ø§ Ø³Ø±ÙˆØ±Ø§Ù† Ø¹Ø²ÛŒØ² ØªÙ‚Ø§Ø¶Ø§ Ù…ÛŒÚ©Ù†ÛŒÙ… Ø§ÛŒØ¯Ù‡ - Ù¾ÛŒØ´Ù†Ù‡Ø§Ø¯ Ùˆ Ù‡Ù…Ú†Ù†ÛŒÙ† Ù†Ù‚Ø¯ÛŒ Ø¨Ø± Ú©Ø§Ø±Ú©Ø±Ø¯ ÙˆØ¨â€ŒØ³Ø§ÛŒØª Ø¯Ø§Ø±ÛŒØ¯ Ø¨Ø§ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² ØµÙØ­Ù‡ Ø§Ø±ØªØ¨Ø§Ø· Ø¨Ø§ Ø§Ù†Ø¬Ù…Ù† Ùˆ ÛŒØ§ Ø§ÛŒÙ…ÛŒÙ„ Ø¯Ø±Ø§Ø±ØªØ¨Ø§Ø· Ø¨Ø§Ø´ÛŒØ¯ ØªØ§ Ø¨ØªÙˆÙ†ÛŒÙ… Ù‡Ø±Ú†Ù‡ Ø¨Ù‡ØªØ± Ø§ÛŒÙ† Ø¨Ø³ØªØ± Ø±Ø§ ØªÙˆØ³Ø¹Ù‡ Ø¨Ø¯ÛŒÙ… Ù‡Ù…Ú†Ù†ÛŒÙ† Ø§Ú¯Ø± ÛŒÚ© ØªÙˆØ³Ø¹Ù‡ Ø¯Ù‡Ù†Ø¯Ù‡ Ùˆ ÙØ±Ø¯ ÙÙ†ÛŒ Ù‡Ø³ØªÛŒØ¯ ØªÙ…Ø§Ù… Ø§ÛŒÙ† Ø³ÙˆØ±Ø³ Ú©Ø¯ Ù‡Ø§ÛŒ Ø§ÛŒÙ† ÙˆØ¨â€ŒØ³Ø§ÛŒØª Ø¢Ø²Ø§Ø¯Ø§Ù†Ù‡ Ø¯Ø± Ø¯Ø³ØªØ±Ø³ Ø¹Ù…ÙˆÙ… Ù‚Ø±Ø§Ø± Ø¯Ø§Ø±Ø¯ Ø¨Ø§ Ù…Ø±Ø§Ø¬Ø¹Ù‡ Ø¨Ù‡ Ú¯ÛŒØªÙ‡Ø§Ø¨ Ù…ÛŒØªÙˆÙ†ÛŒØ¯ ØªØºÛŒÛŒØ±Ø§Øª Ù…Ù†Ø§Ø³Ø¨ Ø±Ø§ Ø§Ø¹Ù…Ø§Ù„ Ú©Ù†ÛŒØ¯. ØªÙ…Ø§Ù… Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ù‡Ø§ÛŒ ØªØºÛŒÛŒØ± Ø¨Ø±Ø±Ø³ÛŒ Ù…ÛŒØ´ÙˆÙ†Ø¯."
author = "Mehran ALam Beigi"
address = "ØªÙ‡Ø±Ø§Ù†, Ù¾ÙˆÙ†Ú© Ø´Ù…Ø§Ù„ÛŒ Ø¨Ù„ÙˆØ§Ø± Ø§Ù…Ø§Ù… Ø­Ø³Ù† Ø¯Ø§Ù†Ø´Ú©Ø¯Ù‡ ÙÙ†ÛŒ Ù…Ù‡Ù†Ø¯Ø³ÛŒ Ø¢Ø²Ø§Ø¯ Ø§Ø³Ù„Ø§Ù…ÛŒ - Ù†ÛŒØ§ÛŒØ´"
mobile = "+989211756034"
email = "info@cabea.ir"
contact_form_action = "#"
google_analitycs_id = ""
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = ""
mailchimp_form_name = ""

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "35.762046"
map_longitude = "51.339170"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

# [[params.social]]
# title = "facebook"
# icon = "ti-facebook"
# link = "#"

[[params.social]]
title = "telegram"
icon = "ti-telegram"
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" 
link = "https://instagram.com/bme_tehranmarkaz"

[[params.social]]
title = "github"
icon = "ti-github"
link = "https://github.com/Mehranalam/Medical-Engineering-Association"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "https://linkedin.com/in/mehranalam"




[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
home = "Ø®Ø§Ù†Ù‡"
# copyright
copyright = "This website was developed by [Mehran Alam Beigi](https://linkedin.com/in/mehranalam) and its source is available as open source."

[[Languages.en.menu.main]]
name = "Ù¾Ú˜ÙˆÙ‡Ø´ Ù‡Ø§ Ùˆ Ù…Ù‚Ø§Ù„Ø§Øª"
url = "research/"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø¯ÛŒØ§Ø±Ø§ğŸ’™"
  url = "https://diara-token.github.io/Diara.ir/"
  
  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø§Ø³Ø§ØªÛŒØ¯"
  url = "teacher/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø§Ø·Ù„Ø§Ø¹ Ø±Ø³Ø§Ù†ÛŒ"
  url = "notice/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø³Ù…ÛŒÙ†Ø§Ø± Ù‡Ø§"
  url = "event/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø¹Ø¶ÙˆÛŒØª Ø¯Ø± Ø§Ù†Ø¬Ù…Ù†"
  url =  "form/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ù¾Ø§Ø¯Ú©Ø³Øªâ€ŒÙ‡Ø§"
  url = "podcast/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ù…Ø¬Ù„Ø§Øª Ùˆ Ù…Ø§Ù‡â€ŒÙ†Ø§Ù…Ù‡"
  url = "magazine/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "ØªØ§Ù„Ø§Ø± Ø§ÙØªØ®Ø§Ø±Ø§Øª"
  url = "honors/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ø¯ÙˆØ±Ù‡ Ùˆ Ú©Ø§Ø±Ú¯Ø§Ù‡ Ù‡Ø§"
  url = "course/"

  [[Languages.en.menu.main]]
  parent = "ØµÙØ­Ø§Øª ØªÚ©Ù†ÛŒÚ©Ø§Ù„"
  name = "Ù†ÙˆÛŒØ³Ù†Ø¯Ú¯Ø§Ù†"
  url = "author/"
  
[[Languages.en.menu.main]]
name = "Ù…Ù‚Ø§Ù„Ø§Øª Ø§Ù†Ø¬Ù…Ù†"
url = "blog/"
weight = 4

[[Languages.en.menu.main]]
name = "Ø§Ø±ØªØ¨Ø§Ø·"
url = "contact/"
weight = 5

[[Languages.en.menu.main]]
  name = "Ù…Ø´Ø§Ø±Ú©Øª"
  url = "scholarship/"
  weight = 6

# main menu
[[Languages.en.menu.main]]
  name = "Ø¯Ø±Ø¨Ø§Ø±Ù‡ Ù…Ø§"
  url = "about/"
  weight = 7

# footer menu

[[Languages.en.menu.footer]]
name = "Ø§Ø³Ø§ØªÛŒØ¯"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "Ø§Ø·Ù„Ø§Ø¹ÛŒÙ‡"
url = "notice/"

[[Languages.en.menu.footer]]
name = "Ø³Ù…ÛŒÙ†Ø§Ø± Ùˆ Ø±ÙˆÛŒØ¯Ø§Ø¯"
url = "event/"

[[Languages.en.menu.footer]]
name = "Ø¯ÛŒØ§Ø±Ø§ â£ï¸"
url = "https://diara-token.github.io/Diara.ir/"

[[Languages.en.menu.footer]]
name = "Ù¾Ú˜ÙˆÙ‡Ø´"
url = "research/"
